package com.jera.caracterisiticsv1.ui.components

import com.jera.caracterisiticsv1.R

object BrandLogoProvider {

    private val logoMap: Map<String, Int> = mapOf(
        "acura"          to R.drawable.brand_acura,
        "alfa romeo"     to R.drawable.brand_alfa_romeo,
        "alfa-romeo"     to R.drawable.brand_alfa_romeo,
        "aston martin"   to R.drawable.brand_aston_martin,
        "aston-martin"   to R.drawable.brand_aston_martin,
        "audi"           to R.drawable.brand_audi,
        "bentley"        to R.drawable.brand_bentley,
        "bmw"            to R.drawable.brand_bmw,
        "bugatti"        to R.drawable.brand_bugatti,
        "buick"          to R.drawable.brand_buick,
        "cadillac"       to R.drawable.brand_cadillac,
        "chevrolet"      to R.drawable.brand_chevrolet,
        "chevy"          to R.drawable.brand_chevrolet,
        "chrysler"       to R.drawable.brand_chrysler,
        "citroen"        to R.drawable.brand_citroen,
        "citroën"        to R.drawable.brand_citroen,
        "dacia"          to R.drawable.brand_dacia,
        "dodge"          to R.drawable.brand_dodge,
        "ferrari"        to R.drawable.brand_ferrari,
        "fiat"           to R.drawable.brand_fiat,
        "ford"           to R.drawable.brand_ford,
        "genesis"        to R.drawable.brand_genesis,
        "honda"          to R.drawable.brand_honda,
        "hyundai"        to R.drawable.brand_hyundai,
        "infiniti"       to R.drawable.brand_infiniti,
        "infinity"       to R.drawable.brand_infiniti,
        "jaguar"         to R.drawable.brand_jaguar,
        "jeep"           to R.drawable.brand_jeep,
        "kia"            to R.drawable.brand_kia,
        "koenigsegg"     to R.drawable.brand_koenigsegg,
        "lamborghini"    to R.drawable.brand_lamborghini,
        "land rover"     to R.drawable.brand_land_rover,
        "land-rover"     to R.drawable.brand_land_rover,
        "lexus"          to R.drawable.brand_lexus,
        "lincoln"        to R.drawable.brand_lincoln,
        "maserati"       to R.drawable.brand_maserati,
        "mazda"          to R.drawable.brand_mazda,
        "mclaren"        to R.drawable.brand_mclaren,
        "mercedes"       to R.drawable.brand_mercedes_benz,
        "mercedes-benz"  to R.drawable.brand_mercedes_benz,
        "mercedes benz"  to R.drawable.brand_mercedes_benz,
        "mini"           to R.drawable.brand_mini,
        "mitsubishi"     to R.drawable.brand_mitsubishi,
        "nissan"         to R.drawable.brand_nissan,
        "opel"           to R.drawable.brand_opel,
        "pagani"         to R.drawable.brand_pagani,
        "peugeot"        to R.drawable.brand_peugeot,
        "porsche"        to R.drawable.brand_porsche,
        "renault"        to R.drawable.brand_renault,
        "rolls royce"    to R.drawable.brand_rolls_royce,
        "rolls-royce"    to R.drawable.brand_rolls_royce,
        "seat"           to R.drawable.brand_seat,
        "skoda"          to R.drawable.brand_skoda,
        "škoda"          to R.drawable.brand_skoda,
        "smart"          to R.drawable.brand_smart,
        "subaru"         to R.drawable.brand_subaru,
        "tesla"          to R.drawable.brand_tesla,
        "toyota"         to R.drawable.brand_toyota,
        "volkswagen"     to R.drawable.brand_volkswagen,
        "vw"             to R.drawable.brand_volkswagen,
        "volvo"          to R.drawable.brand_volvo,
    )

    /** Devuelve el resource ID del logo para la marca dada, o null si no existe. */
    fun getLogoRes(brandName: String): Int? =
        logoMap[brandName.trim().lowercase()]
}
